
== The Rime of the Product Manager


=== 1 - A Ruined Man

[role=scene]
Int. - A hotel conference center - day

[role=transition]
FADE IN

At a busy technology conference, several attendees walk down the hall together between sessions. A haggard middle-aged man in torn clothes approaches...

[role=dialog]
.Narrator
It is a Product Manager +
And he stoppeth one of three +
"By thy backlog deep and ordered wise +
Now wherefore stopp'st thou me?" +

The conference-goer gestures into a breakout room with several people already seated. He is trying to dodge this interruption, which is more than a little bit socially inappropriate.

[role=dialog]
.Narrator
"The breakout's doors are opened wide +
And I must find a seat +
The plugs are few, the slides are new, +
The speaker I would meet!" +

The old man grabs the conference-goer and starts to shout his story. Unimpressed, the conference goer tries to shake him off, almost becoming violent.

[role=dialog]
.Narrator
He holds him with his skinny hand +
"My startup failed!" said he +
"Mere dimes a dozen, 'startups' are! +
Unhand and let me be!" +

The old man now fixes the younger man in eye contact, and the two finally connect. The young man's attention is arrested.

[role=dialog]
.Narrator
He holds him with his glittering eye, +
The conference-goer stood still, +
And listens like a three-years child, +
The PM hath his will. +

As the crowd thins, the conference-goer relents and sits down to listen, captive to the PM's story.

[role=dialog]
.Narrator
The Conference-Goer sat on a bag: +
He cannot choose but hear; +
And thus spake on that tired man, +
The Product Manager. +


=== 2 - Flashback to Founding

[role=scene]
Ext. - A coffee shop on a busy LoDo street - day

Two tech startup +Co-founders+ are walking down a LoDo street and into a coffee shop.

[role=dialog]
.Narrator
We started in a coffee shop +
Upon a city street +
UI mocks were drink to us +
And code our only meat +

// scene 2.1
//
[role=scene]
Int. - The coffee shop - day

The +Co-founders+ are coding enthusiastically on their laptops, occasionally exchanging a few words, having a debate, or scratching out design diagrams on paper. They are obviously focused and enjoying themselves. They are changing the world.

[role=dialog]
.Narrator
We coded long, we coded hard +
We coded day and night +
We coded like our days would end +
Except we code aright +

[role=dialog]
.Narrator
From in the zone we did our work +
We all knew what do to +
With focus like a team obsessed +
We built our vision true +

[role=dialog]
.Narrator
None among us told his peer +
The features he should build +
If we had played the manager +
Our ethic we'd have killed +

// scene 2.2
[role=scene]
Int. - The coffee shop - night

The +co-founders+ are ready to launch the first production version of their site. They are nervous but excited, ready finally to share their product with the world, apprehensive about its performance in production, and afraid that no one will care about what they've done. The look at each other and hit enter on the final Git push to do the deploy, uncertain of what the future brings.

[role=dialog]
.Narrator
Then one dark night, we launched the site +
Our hearts besot with hope +
In Graphite's thrall we watched it all +
And none dared even joke/_____caught every throat +

// scene 2.3
// 
[role=scene]
Int. - The coffee shop - day

Looking at flat +traffic graphs+, the +co-founders+ are discouraged. Iwantto workeematg


// This stanza sucks
[role=dialog]
.Narrator
We watched the charts all day and night +
Promoting less than gently +
We'd die to win the favor of +
The Valley cognoscienti +

Staring off into space, one of the +co-founders+ happens to catch an improving +traffic graph+ on the screen. Something big has happened, and traffic is taking off. They look at each other excitedly. The +traffic graph+ shows spiking traffic.

[role=dialog]
.Narrator
We scored the write-ups we were after +
And traffic started spiking +
The servers groaned under the load +
All dynos running to the hilt +
We dared to think we might have built +
A product of our liking +

// scene 2.4
The +co-founders+ are high-fiving and hugging in the joy and elation of the first real sign of market success. They look at increasing +traffic stats+ on a screen and can't believe this is happening to them.

[role=dialog]
.Narrator
So active users multiplied +
Signups beyond counting +
More users than we'd dared hope +
Soon put to rest our doubting +

// scene 2.5
The screen shows an animated +revenue chart+ moving up and to the right. One +co-founder+ brings two +fancy coffees+ to the other, and they toast their success.


// scene 2.6
The +co-founders+ sit down and start to plan the next features they want to implement.

[role=dialog]
.Narrator
We bathed in growing revenue +
All metrics in our favor +
//These two lines suck +
And users happy without limit +
Such a memory to savor! +


=== 3 - Funding

[role=scene]
Int - VC Office - day

The room is not opulent, but clearly evinces the trappings of status and affluence. Two middle-aged men sit at the table.

The +VC Fund Manager+ and an assistant look over some printed documents and examine a web site on a laptop screen. They are undeniably impressed, despite a veneer of jaded reluctance to believe that any new venture is really worthwhile.

[role=scene]
Int - Coffee Shop - night

Seated in a different corner of the room, one of the +co-founders+ gets a phone call from a contact called +G Money+. He answers the phone, listens with interest, and reacts with stunned surprise at being offered venture funding. He and other +co-founder+ high-five and hug in joy.

[role=dialog]
.Narrator
The VCs saw what we had built +
And offered to us terms +
That we could scarcely not accept +
—so much we had to learn! +

[role=scene]
Int - VC Office - day

The room is not opulent, but clearly evinces the trappings of status and affluence. A middle-aged man in a sportcoat sits across the table.

The +co-founders+ sign papers with the +VC Fund Manager+. They stand up and all shake hands, excited to begin the real work of launching a company and becoming rich beyond the dreams of avarice.

[role=dialog]
.Narrator
We closed an A round and we thought +
Success was now in hand! +
Who could but think that capital +
Had ratified our plans? +

[role=scene]
Int - Gmail web client - day

The +co-founders+ write emails enticing former co-workers to come work for them. Several emails pan across the screen, each new one overlapping the previous one, as hiring proceeds over the course of many months.

[role=dialog]
.Narrator
With all due youthful confidence +
We set ourselves to hiring +
We poached, cajoled, and outbid for +
The staff of our desiring +

[role=scene]
int - startup office - day

An open workspace is populated by a diverse crowd of young engineers and designers. The open tables are festooned with MacBooks, and developers sitting on Aerons busily peck away at their keyboards, engrossed in their work. Occasionally some engineers sit up and sketch things out at a whiteboard. The company is energetic and happy.

[role=dialog]
.Narrator
And what with shiny laptops humming +
Could all these hackers do? +
They built the features users wanted +
Feature on feature accrued +

[role=dialog]
.Narrator
The product grew and users knew +
We listened to them closely +
We always tried to meet their needs +
And we succeeded...mostly +

[role=scene]
int - startup office - night

Two tired developers and a +co-founder+ stand up from a long day's work and walk over to the mini-bar. They fix some drinks and unwind, ominously forgetting work. They continue drinking and sit down to play some video games long into the night.

[role=dialog]
.Narrator
We coded long, we coded hard +
But a hacker needs to rest! +
With VC funds we bought some cheer +
And wine and gin and Scotch and beer +
We worked and drank and worked 'til near +
Our work was not our best +

[role=dialog]
.Narrator
Now such a team could scarce avoid +
A Providential chastening +
No one could know that this new flow +
Had been our failure hastening +


=== 4 - Product

[role=scene]
int - startup office - day

Months pass. 

A +co-founder+ walks languidly into work, late. Rapid hiring has made the office a little more crowded, but developers are less focused and are visibly using Facebook, playing paddle games, and generally screwing around.

[role=dialog]
.Narrator
Those early days of coding hard +
In cafes on the cheap? +
Were gone and in their place we’d built +
A comp’ny growing weak +

A +developer+ sits back from her keyboard, texting on her iPhone.

Another developer plays @zerowidth's Asteroids clone on his computer.

Two other developers chat lazily about sports, office gossip, or anything other than the product they're building.

The +co-founders+ review a feature checklist written on a whiteboard, realizing that the features are really non-starters that aren't going to move the product forward at all.

[role=dialog]
.Narrator
No longer was each eager coder +
Focused on our users +
No vision animated them +
No judgment was within their ken +
We looked at our new features then +
We judged these features losers +

Developers sit and play video games. Partially-drunk beers and dirty dishes are visible at desks.

[role=dialog]
.Narrator
Our devs were not so focused as +
We had been at our founding +
They needed help to think aright +
They needed to have grounding +

The +co-founders+ are talking about the company malaise, and one gets the idea that the other should become a +product manager+.

The new +Product Manager+ stands in front of a +whiteboard+, with his whole team listening. He points to the words "product manager" on the +whiteboard+, indicating his new role, while will revitalize the company.

[role=dialog]
.Narrator
We all agreed the thing we’d need +
Without a doubt averred +
I’d hang up coding and become +
A Product Manager +

The +whiteboard+ now shows +Scrum swimlanes+ (todo, in process, to verify, done) with post-it notes on each one. The +product manager+ cajoles developers to come up to the board to talk about stories, and move post-it notes around. Developers seem uninterested.

[role=dialog]
.Narrator
The founders’ product vision now +
Came through the medium +
Of story cards and backlogged  +
... +

The +Product Manager+ is sitting at a desk, diligently writing story cards on post it notes. He writes "OAuth2 support," "Admins can issue credits," and "Users can pay."

The +developers+ aren't really that interested in story cards. The +product manager+ is pointing at columns and angrily asking the +developers+ if stories should now has trouble getting developers to tend to the story cards. One of them stares off into space, and he slaps him to get his attention. They resent him, and he has to badger them to get their interest.

The +developers+ walk away from the +whiteboard+ in board disgust.

[role=dialog]
.Narrator
And I had done a hellish thing, +
And it would work 'em woe: +
For all had seen, I'd killed the team +
That made the comp’ny grow. +
Ah wretch! said they, the team to slay, +
That made the comp’ny grow! +

A +developer+ taps a pencil on her desk, not typing. Another opens up a Facebook tab. Another crinkles a story card with suppressed, passive anger. One sleeps. They are not motivated and not working.

[role=dialog]
.Narrator
Day after day, day after day, +
// This sucks a little
We stuck, no more would we grow; +
As idle as a painted team +
Upon a painted repo +

Some developers hang out in the kitchen, rifling around for snacks. 

A developer sits at his computer, breathing through his mouth, staring into space.

[role=dialog]
.Narrator
Product, product everywhere +
And happiness did shrink +
Product, product everywhere +
Nor anyone to think +


=== 5 - Decadence and Failure

No longer interested in talking to the +co-founders+, the +VC Fund Manager+ walks along the street talking on his phone. The +co-founders+ try to get his attention, but he brushes them off like a couple of annoying kids.

[role=dialog]
.Narrator
Revenue flatlines, B round doesn't close

The +co-founders+ nervously explain things to a group of staff huddled around them that they don't have a whole lot of runway left. The developers looks worried, but not because they want the company to survive. They are worried about where they land next.

[role=dialog]
.Narrator
Morale drops

A +developer+ gives his notice to both +co-founders+. He holds up a GitHub sticker, indicating that he is going to work for them. The +co-founders+ wish him luck and shake his hand.

[role=dialog]
.Narrator
Devs start to quit

The other +co-founder+ breaks the news to the +product manager+ that she is going to be leaving to start a new company.

[role=dialog]
.Narrator
A co-founder leaves start a new company

The +product manager+ walks out of an empty office and looks around in heartbroken resignation. He turns the lights out and leaves.

[role=dialog]
.Narrator
PM escapes

[role=transition]
Fade through black back to the conference.



=== 6 - A Changed Developer

[role=dialog]
.Narrator
Ever since then I've had to tell this story from time to time (agony if I don't)

[role=dialog]
.Narrator
Back to the conference, people coming out of the room

// scene 6.3
[role=scene]
Int - coffee shop - night

[role=transition]
Slow motion

The +co-founders+ are talking, debating, coding, desinging, and loving life in the early days of their startup.

[role=dialog]
.Narrator
Devs have to love their users

[role=dialog]
.Narrator
Have to know and love their domain

[role=dialog]
.Narrator
Doesn't matter what the domain is

[role=scene]
Int - startup office - day

The +co-founders+ are working together as peers with the newly-hired +developers+.They are collaborating joyfully, building a product together.


[role=dialog]
.Narrator
Creative people have to do what they are in interested in doing

[role=dialog]
.Narrator
They can't be force-marched into greatness



[role=scene]
Int - conference - day

[role=dialog]
.Narrator
I have to tell people this story

[role=dialog]
.Narrator
The old PM, whose eye is bright, +
Whose blog with age is stale, +
Is gone; and now the Conference-Goer +
Departs the conference vale. +

[role=dialog]
.Narrator
He leaves like one that hath been stunned, +
And is of sense forlorn: +
A sadder, wiser hacker then +
He rose the morrow morn. +

[role=transition]
FADE TO BLACK.

