
== The Rime of the Product Manager


=== 1 - A Ruined Man

[[SCENE_1.1]]
[role=scene]
Int. - A hotel conference center - day

[role=transition]
FADE IN

At a busy technology conference, several attendees walk down the hall together between sessions. A haggard middle-aged man in torn clothes approaches...

[role=dialog]
.Narrator
It is a Product Manager +
And he stoppeth one of three +
"By thy backlog deep and ordered wise +
Now wherefore stopp'st thou me?" +

The conference-goer gestures into a breakout room with several people already seated. He is trying to dodge this interruption, which is more than a little bit socially inappropriate.

[role=dialog]
.Narrator
"The breakout's doors are opened wide +
And I must find a seat +
The plugs are few, the slides are new, +
The speaker I would meet!" +

The old man grabs the conference-goer and starts to shout his story. Unimpressed, the conference goer tries to shake him off, almost becoming violent.

[role=dialog]
.Narrator
He holds him with his skinny hand +
"My startup failed!" said he +
"Mere dimes a dozen, 'startups' are! +
Unhand and let me be!" +

The old man now fixes the younger man in eye contact, and the two finally connect. The young man's attention is arrested.

[role=dialog]
.Narrator
He holds him with his glittering eye, +
The conference-goer stood still, +
And listens like a three-years child, +
The PM hath his will. +

As the crowd thins, the conference-goer relents and sits down to listen, captive to the PM's story.

[role=dialog]
.Narrator
The Conference-Goer took his seat: +
He cannot choose but hear; +
And thus spake on that tired man, +
The Product Manager. +


=== 2 - Flashback to Founding

[[SCENE_2.0]]
[role=scene]
Ext. - A coffee shop on a busy LoDo street - day

Two tech startup +Co-founders+ are walking down a LoDo street and into a coffee shop.

[role=dialog]
.Narrator
We started in a coffee shop +
Upon a city street +
UI mocks were drink to us +
And code our only meat +

[[SCENE_2.1]]
[role=scene]
Int. - The coffee shop - day

The +Co-founders+ are coding enthusiastically on their laptops, occasionally exchanging a few words, having a debate, or scratching out design diagrams on paper. They are obviously focused and enjoying themselves. They are changing the world.

[role=dialog]
.Narrator
We coded long, we coded hard +
We coded day and night +
We coded like our days would end +
Except we code aright +

[role=dialog]
.Narrator
None among us told his peer +
The features he should build +
If we had played the manager +
Our vision we'd have killed +

[[SCENE_2.2]]
[role=scene]
Int. - The coffee shop - night

The +co-founders+ are ready to launch the first production version of their site. They are nervous but excited, ready finally to share their product with the world, apprehensive about its performance in production, and afraid that no one will care about what they've done. The look at each other and hit enter on the final Git push to do the deploy, uncertain of what the future brings.

[role=dialog]
.Narrator
Then one dark night, we launched the site +
Our hearts besot with hope +
In Graphite's thrall we watched it all +
And dread caught every throat +

[[SCENE_2.3]]
[role=scene]
Int. - The coffee shop - day

Looking at flat +traffic graphs+, the +co-founders+ are discouraged.

// This stanza sucks
[role=dialog]
.Narrator
We watched the charts all day and night +
Frowning, sighing gently +
Our only goal, the favor of +
The Valley Cognoscienti +

Staring off into space, one of the +co-founders+ happens to catch an improving +traffic graph+ on the screen. Something big has happened, and traffic is taking off. They look at each other excitedly. The +traffic graph+ shows spiking traffic.

[role=dialog]
.Narrator
We got the mentions we were after +
Traffic started spiking +
The servers groaned under the load +
All VMs running to the hilt +
We dared to think we might have built +
A product of our liking +

[[SCENE_2.4]]
The +co-founders+ are high-fiving and hugging in the joy and elation of the first real sign of market success. They look at increasing +traffic stats+ on a screen and can't believe this is happening to them.

[[SCENE_2.5]]
The screen shows an animated +revenue chart+ moving up and to the right. One +co-founder+ brings two +fancy coffees+ to the other, and they toast their success.

[role=dialog]
.Narrator
We bathed in growing revenue +
All metrics in our favor +
Subscribers new, renewals too +
Made these the days to savor +


=== 3 - Funding

[role=scene]
Int - VC Office - day

[[SCENE_3.1]]
The room is not opulent, but clearly evinces the trappings of status and affluence. Two middle-aged men sit at the table.

The +VC Fund Manager+ and an assistant look over some printed documents and examine a web site on a laptop screen. They are undeniably impressed, despite a veneer of jaded reluctance to believe that any new venture is really worthwhile.

[[SCENE_3.2]]
[role=scene]
Int - Coffee Shop - night

Seated in a different corner of the room, one of the +co-founders+ gets a phone call from a contact called +G Money+. He answers the phone, listens with interest, and reacts with stunned surprise at being offered venture funding. He and other +co-founder+ high-five and hug in joy.

[role=dialog]
.Narrator
The VCs saw what we had built +
And offered to us terms +
That we could scarcely not accept +
—so much we had to learn! +

[[SCENE_3.3]]
[role=scene]
Int - VC Office - day

The room is not opulent, but clearly evinces the trappings of status and affluence. A middle-aged man in a sport coat sits across the table.

The +co-founders+ sign papers with the +VC Fund Manager+. They stand up and all shake hands, excited to begin the real work of launching a company and becoming rich beyond the dreams of avarice.

[role=dialog]
.Narrator
We closed an A round and we thought +
Success was now in hand! +
Who could but think that capital +
Had ratified our plans? +

[[SCENE_3.4]]
[role=scene]
Int - Gmail web client - day

The +co-founders+ write emails enticing former co-workers to come work for them. Several emails pan across the screen, each new one overlapping the previous one, as hiring proceeds over the course of many months.

[role=dialog]
.Narrator
With all due youthful confidence +
We set ourselves to hiring +
We poached, cajoled, and outbid for +
The staff of our desiring +

[[SCENE_3.5]]
[role=scene]
int - startup office - day

An open workspace is populated by a diverse crowd of young engineers and designers. The open tables are festooned with MacBooks, and developers sitting on Aerons busily peck away at their keyboards, engrossed in their work. Occasionally some engineers sit up and sketch things out at a whiteboard. The company is energetic and happy.

[role=dialog]
.Narrator
And what with shiny laptops humming +
Could all these hackers do? +
They built the features users wanted +
Feature on feature accrued +

[[SCENE_3.6]]
[role=scene]
int - startup office - night

Two tired developers and a +co-founder+ stand up from a long day's work and walk over to the mini-bar. They fix some drinks and unwind, ominously forgetting work. They continue drinking and sit down to play some video games long into the night.

[role=dialog]
.Narrator
We coded long, we coded hard +
But a hacker needs to rest! +
With VC funds we bought some cheer +
And wine and gin and Scotch and beer +
We worked and drank and worked 'til near +
Our work was not our best +

[role=dialog]
.Narrator
Now such a team could scarce avoid +
A Providential chastening +
No one could know that this new flow +
Had been our failure hastening +


=== 4 - Product

[[SCENE_4.1]]
[role=scene]
int - startup office - day

Weeks pass.

A +co-founder+ walks languidly into work, late. Rapid hiring has made the office a little more crowded, but developers are less focused and are visibly using Facebook, playing paddle games, and generally screwing around.

[role=dialog]
.Narrator
Those early days of coding hard +
In cafes on the cheap? +
Were gone and in their place we’d built +
A comp’ny growing weak +

[[SCENE_4.2]]
A +developer+ sits back from her keyboard, texting on her iPhone.

Another developer plays @zerowidth's Asteroids clone on his computer.

Two other developers chat lazily about sports, office gossip, or anything other than the product they're building.

[[SCENE_4.3]]
The +co-founders+ review a feature checklist written on a whiteboard, realizing that the features are really non-starters that aren't going to move the product forward at all. Ex: "Surface Pro support," "Mongo cluster?," "Gamification"

[role=dialog]
.Narrator
No longer was each eager coder +
Focused on our users +
No vision animated them +
No judgment was within their ken +
We looked at our new features then +
We judged these features losers +

[[SCENE_4.4]]
Developers sit and play video games. Partially-drunk beers and dirty dishes are visible at desks.

[[SCENE_4.5]]
The +co-founders+ are talking about the company malaise, and one gets the idea that the other should become a +product manager+.

[[SCENE_4.6]]
The new +Product Manager+ stands in front of a +whiteboard+, with his whole team listening. He points to the words "product manager" on the +whiteboard+, indicating his new role, while will revitalize the company.

[role=dialog]
.Narrator
We all agreed the thing we’d need +
Without a doubt averred +
I’d hang up coding and become +
A Product Manager +

[[SCENE_4.7]]
The +whiteboard+ now shows +Scrum swimlanes+ (todo, in process, to verify, done) with post-it notes on each one. The +product manager+ cajoles developers to come up to the board to talk about stories, and move post-it notes around. Developers seem uninterested.


[role=dialog]
.Narrator
The founders’ product vision now +
Came through the medium +
Of story cards and backlogged  +
Scars of endless tedium +

[[SCENE_4.8]]
The +Product Manager+ is sitting at a desk, diligently writing story cards on post it notes. He writes "OAuth2 support," "Admins can issue credits," and "Users can pay."

[[SCENE_4.9]]
The +developers+ aren't really that interested in story cards. The +product manager+ is pointing at columns and angrily asking the +developers+ if stories should now has trouble getting developers to tend to the story cards. One of them stares off into space, and he slaps him to get his attention. They resent him, and he has to badger them to get their interest.

The +developers+ walk away from the +whiteboard+ in board disgust.

[role=dialog]
.Narrator
And I had done a hellish thing, +
And it would work 'em woe: +
For all had seen, I'd killed the team +
That made the comp’ny grow. +
Ah wretch! said they, the team to slay, +
That made the comp’ny grow! +

[[SCENE_4.10]]
A +developer+ taps a pencil on her desk, not typing. Another opens up a Facebook tab. Another crinkles a story card with suppressed, passive anger. One sleeps. They are not motivated and not working.

[role=dialog]
.Narrator
Day after day, day after day, +
We stuck, no more would we grow; +
As idle as a painted team +
Upon a painted repo +

Some developers hang out in the kitchen, rifling around for snacks.

A developer sits at his computer, breathing through his mouth, staring into space.

[role=dialog]
.Narrator
Process, process everywhere +
And happiness did shrink +
Process, process everywhere +
Nor anyone to think +


=== 5 - Decadence and Failure

[[SCENE_5.1]]
No longer interested in talking to the +co-founders+, the +VC Fund Manager+ walks along the street talking on his phone. The +co-founders+ try to get his attention, but he brushes them off like a couple of annoying kids.

// Revenue flatlines, B round doesn't close
[role=dialog]
.Narrator
Subscription growth had flatlined +
And our runway shrank to nothing +
Subscriber acquisition cost +
So bloated we were blushing +

[[SCENE_5.2]]
The +co-founders+ nervously explain things to a group of staff huddled around them that they don't have a whole lot of runway left. The developers looks worried, but not because they want the company to survive. They are worried about where they land next.

[[SCENE_5.3]]
A +developer+ gives his notice to both +co-founders+. He holds up a GitHub sticker, indicating that he is going to work for them. The +co-founders+ wish him luck and shake his hand.

[role=dialog]
.Narrator
That dream team that we'd hired then? +
No longer could they trust +
We'd give an exit worth their time +
So left they as they must +


[[SCENE_5.4]]
The other +co-founder+ breaks the news to the +product manager+ that she is going to be leaving to start a new company.

[role=dialog]
.Narrator
If it were only staff I lost +
Survive I just have might +
Buy my partner joined the tide +
And left me in my plight +

[[SCENE_5.5]]
The +product manager+ walks out of an empty office and looks around in heartbroken resignation. He turns the lights out and leaves.

[role=dialog]
.Narrator
There was nothing left to build +
The vision we had started +
I could only turn and leave +
A founder, broken-hearted +

[role=transition]
Fade through black back to the conference.



=== 6 - A Changed Developer

[[SCENE_6.1]]
[role=scene]
Int - conference - day

Back in the conference, the +product manager+ is finishing his story to the +conference-goer+. The session is now over, and conference +attendees+ are coming out of the room.

[role=dialog]
.Narrator
And now I fly from show to show +
Spreading far my story +
To coders young who've yet to learn +
What made my heart so hoary +

[[SCENE_6.2]]
[role=scene]
Int - coffee shop - night

[role=transition]
Slow motion

The +co-founders+ are talking, debating, coding, designing, and loving life in the early days of their startup.

[role=dialog]
.Narrator
It doesn't matter what your scale +
Nor where you got your funding +
If devs don't love their users then +
Your futures will be plunging +

[role=dialog]
.Narrator
The vision that you started with +
To set the world aright? +
Must be spread to everyone +
Who gives your product life +

[[SCENE_6.3]]
[role=scene]
Int - startup office - day

The +co-founders+ are working together as peers with the newly-hired +developers+. They are collaborating joyfully, building a product together.

[role=dialog]
.Narrator
The sub-creators of the world +
Must love the things they make +
If you would lead, then you're the one +
To spark their hearts awake +

[role=dialog]
.Narrator
They can't be bought with snacks or drink +
And process least of all +
Can bring the flush of health back to +
Coders once they fall +


[[SCENE_6.4]]
[role=scene]
Int - conference - day

The +product manager+ is done telling his story, and turns to walk out without saying goodbye. The +conference-goer+ is stupefied, shorn of all his previous assumptions about vocation and significance. He walks away sadly, but with a hint of hope that life will be better.

[role=dialog]
.Narrator
And now I fly from show to show +
Telling wide my story +
To coders young who may yet learn +
Where lies their future glory +

[role=dialog]
.Narrator
The old PM, whose eye is bright, +
Whose blog with age is stale, +
Is gone; and now the Conference-Goer +
Departs the conference vale. +

[role=dialog]
.Narrator
He leaves like one that hath been stunned, +
And is of sense forlorn: +
A sadder, wiser hacker then +
He rose the morrow morn. +

[role=transition]
FADE TO WHITE.
