#!/bin/sh

set -e

this=$(readlink "$0" || echo "$0")
root=$(dirname $(dirname "$this"))

$root/script/bootstrap &&
  $root/bin/asciidoctor \
    -a stylesdir=$root/stylesheets \
    -a stylesheet=screenplay.css \
    $root/screenplay/rotpm.asciidoc
